Update Release workflow

diff --git a/.github/workflows/review-release.yml b/.github/workflows/review-release.yml
--- a/.github/workflows/review-release.yml
+++ b/.github/workflows/review-release.yml
@@ -1,4 +1,4 @@
-name: SmallRye Pre Release
+name: SmallRye Review Release
 
 on:
   pull_request:
@@ -17,6 +17,12 @@ jobs:
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           metadata-file-path: '.github/project.yml'
+
+      - name: Validate version
+        if: contains(steps.metadata.outputs.current-version, 'SNAPSHOT')
+        run: |
+          echo '::error::Cannot release a SNAPSHOT version.'
+          exit 1
 
       - uses: radcortez/milestone-review-action@main
         name: milestone review
